/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_1 (
    input [7:0] a,
    input [7:0] b,
    input alufn0,
    input alufn1,
    output reg [7:0] op,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [7:0] tmpsum;
  
  reg xb7;
  
  always @* begin
    if (alufn0 == 1'h1 & alufn1 == 1'h0) begin
      tmpsum = a - b;
    end else begin
      if (alufn0 == 1'h0 & alufn1 == 1'h1) begin
        tmpsum = a * b;
      end else begin
        tmpsum = a + b;
      end
    end
    xb7 = (alufn0 ^ b[7+0-:1]);
    op = tmpsum;
    z = (tmpsum == 8'h00);
    n = tmpsum[7+0-:1];
    v = (a[7+0-:1] & xb7 & (~tmpsum[7+0-:1])) | ((~a[7+0-:1]) & (~xb7) & tmpsum[7+0-:1]);
  end
endmodule
