/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module cube_3 (
    input clk,
    input rst,
    input [63:0] matrix,
    input [5:0] curr,
    output reg [3:0] level,
    output reg [15:0] col
  );
  
  
  
  reg [29:0] M_counter_d, M_counter_q = 1'h0;
  
  reg [1:0] n;
  
  always @* begin
    M_counter_d = M_counter_q;
    
    n = M_counter_q[14+1-:2];
    M_counter_d = M_counter_q + 1'h1;
    level[0+3-:4] = 4'hf;
    level[(n)*1+0-:1] = 2'h0;
    col = matrix[(n)*16+15-:16];
    if (n == curr[0+1-:2]) begin
      col[(curr[2+1-:2])*4+(curr[4+1-:2])*1+0-:1] = 1'h1;
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_counter_q <= 1'h0;
    end else begin
      M_counter_q <= M_counter_d;
    end
  end
  
endmodule
