/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg spi_miso,
    output reg [3:0] spi_channel,
    output reg avr_rx,
    input [5:0] movebtn,
    input startbtn,
    input resetbtn,
    output reg [3:0] cube_level,
    output reg [15:0] cube_col,
    output reg [6:0] segment_part,
    output reg [3:0] segment_LED
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  reg [3:0] M_level_d, M_level_q = 1'h0;
  reg [5:0] M_current_d, M_current_q = 1'h0;
  reg [5:0] M_next_d, M_next_q = 1'h0;
  reg [63:0] M_matrix_d, M_matrix_q = 1'h0;
  reg [5:0] M_score_d, M_score_q = 1'h0;
  wire [6-1:0] M_buttons_movebtn_pressed;
  wire [1-1:0] M_buttons_startpressed;
  wire [1-1:0] M_buttons_resetpressed;
  reg [6-1:0] M_buttons_movebtn;
  reg [1-1:0] M_buttons_start;
  reg [1-1:0] M_buttons_reset;
  ext_io_2 buttons (
    .clk(clk),
    .rst(rst),
    .movebtn(M_buttons_movebtn),
    .start(M_buttons_start),
    .reset(M_buttons_reset),
    .movebtn_pressed(M_buttons_movebtn_pressed),
    .startpressed(M_buttons_startpressed),
    .resetpressed(M_buttons_resetpressed)
  );
  wire [4-1:0] M_cube_level;
  wire [16-1:0] M_cube_col;
  reg [64-1:0] M_cube_matrix;
  reg [1-1:0] M_cube_showcurr;
  reg [6-1:0] M_cube_curr;
  cube_3 cube (
    .clk(clk),
    .rst(rst),
    .matrix(M_cube_matrix),
    .showcurr(M_cube_showcurr),
    .curr(M_cube_curr),
    .level(M_cube_level),
    .col(M_cube_col)
  );
  wire [7-1:0] M_displaySegments_segs;
  wire [4-1:0] M_displaySegments_segmentLED;
  reg [3-1:0] M_displaySegments_state;
  reg [6-1:0] M_displaySegments_score;
  reg [4-1:0] M_displaySegments_level;
  seven_seg_4 displaySegments (
    .clk(clk),
    .rst(rst),
    .state(M_displaySegments_state),
    .score(M_displaySegments_score),
    .level(M_displaySegments_level),
    .segs(M_displaySegments_segs),
    .segmentLED(M_displaySegments_segmentLED)
  );
  localparam CHOOSE_LVL_sm = 3'd0;
  localparam INIT_MAP_sm = 3'd1;
  localparam MOVE_sm = 3'd2;
  localparam CHECK1_sm = 3'd3;
  localparam CHECK_sm = 3'd4;
  localparam WIN_sm = 3'd5;
  
  reg [2:0] M_sm_d, M_sm_q = CHOOSE_LVL_sm;
  
  wire [8-1:0] M_alu_out;
  reg [8-1:0] M_alu_a;
  reg [8-1:0] M_alu_b;
  reg [6-1:0] M_alu_alufn;
  alu_5 alu (
    .a(M_alu_a),
    .b(M_alu_b),
    .alufn(M_alu_alufn),
    .out(M_alu_out)
  );
  
  localparam LEVELS = 512'h89090f9f09990f0f800c166d1667f009911d988b900b999dcc33ce7337ec33cc8888088333033f00800f09990000800990090000000090098000f11f0008f999;
  
  always @* begin
    M_sm_d = M_sm_q;
    M_level_d = M_level_q;
    M_matrix_d = M_matrix_q;
    M_next_d = M_next_q;
    M_score_d = M_score_q;
    M_current_d = M_current_q;
    
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    M_buttons_movebtn = ~movebtn;
    M_buttons_start = ~startbtn;
    M_buttons_reset = ~resetbtn;
    M_cube_matrix = M_matrix_q;
    M_cube_showcurr = 1'h0;
    M_cube_curr = M_current_q;
    cube_col = M_cube_col;
    cube_level = M_cube_level;
    M_alu_alufn = 6'h00;
    M_alu_a = 8'h00;
    M_alu_b = 8'h00;
    M_displaySegments_state = M_sm_q;
    M_displaySegments_score = M_score_q;
    M_displaySegments_level = M_level_q;
    segment_LED = M_displaySegments_segmentLED;
    segment_part = M_displaySegments_segs;
    M_level_d = M_level_q;
    M_current_d = M_current_q;
    M_next_d = M_next_q;
    M_matrix_d = M_matrix_q;
    M_score_d = M_score_q;
    M_sm_d = M_sm_q;
    
    case (M_sm_q)
      CHOOSE_LVL_sm: begin
        M_matrix_d = 64'h0000000000000000;
        if (M_buttons_movebtn_pressed[0+0-:1] & M_level_q < 3'h7) begin
          M_level_d = M_level_q + 1'h1;
        end
        if (M_buttons_movebtn_pressed[1+0-:1] & M_level_q > 1'h0) begin
          M_level_d = M_level_q - 1'h1;
        end
        if (M_buttons_startpressed) begin
          M_sm_d = INIT_MAP_sm;
        end
        rst = M_buttons_resetpressed;
      end
      INIT_MAP_sm: begin
        M_matrix_d = LEVELS[(M_level_q)*64+63-:64];
        M_current_d = 6'h3f;
        M_cube_showcurr = 1'h1;
        M_matrix_d[48+12+3+0-:1] = 1'h0;
        M_next_d = 6'h3f;
        if ((|M_buttons_movebtn_pressed)) begin
          
          case (M_buttons_movebtn_pressed)
            6'h01: begin
              M_next_d[0+1-:2] = M_current_q[0+1-:2] - 1'h1;
            end
            6'h02: begin
              M_next_d[0+1-:2] = M_current_q[0+1-:2] + 1'h1;
            end
            6'h04: begin
              M_next_d[4+1-:2] = M_current_q[4+1-:2] - 1'h1;
            end
            6'h08: begin
              M_next_d[4+1-:2] = M_current_q[4+1-:2] + 1'h1;
            end
            6'h10: begin
              M_next_d[2+1-:2] = M_current_q[2+1-:2] + 1'h1;
            end
            6'h20: begin
              M_next_d[2+1-:2] = M_current_q[2+1-:2] - 1'h1;
            end
          endcase
          M_sm_d = CHECK1_sm;
        end
        if (M_buttons_resetpressed) begin
          M_sm_d = CHOOSE_LVL_sm;
        end
      end
      MOVE_sm: begin
        M_next_d = M_current_q;
        M_cube_showcurr = 1'h1;
        if ((|M_buttons_movebtn_pressed)) begin
          
          case (M_buttons_movebtn_pressed)
            6'h01: begin
              M_next_d[0+1-:2] = M_current_q[0+1-:2] - 1'h1;
            end
            6'h02: begin
              M_next_d[0+1-:2] = M_current_q[0+1-:2] + 1'h1;
            end
            6'h04: begin
              M_next_d[4+1-:2] = M_current_q[4+1-:2] - 1'h1;
            end
            6'h08: begin
              M_next_d[4+1-:2] = M_current_q[4+1-:2] + 1'h1;
            end
            6'h10: begin
              M_next_d[2+1-:2] = M_current_q[2+1-:2] + 1'h1;
            end
            6'h20: begin
              M_next_d[2+1-:2] = M_current_q[2+1-:2] - 1'h1;
            end
          endcase
          M_sm_d = CHECK1_sm;
        end
        if (M_buttons_resetpressed) begin
          if (M_score_q == 1'h0) begin
            M_sm_d = INIT_MAP_sm;
          end else begin
            M_alu_a = M_score_q;
            M_alu_b = 1'h1;
            M_alu_alufn = 6'h01;
            M_score_d = M_alu_out[0+3-:4];
            M_sm_d = INIT_MAP_sm;
          end
        end
      end
      CHECK1_sm: begin
        if (M_matrix_q[(M_next_q[0+1-:2])*16+(M_next_q[2+1-:2])*4+(M_next_q[4+1-:2])*1+0-:1] == 1'h1) begin
          M_matrix_d[(M_next_q[0+1-:2])*16+(M_next_q[2+1-:2])*4+(M_next_q[4+1-:2])*1+0-:1] = 1'h0;
          M_current_d = M_next_q;
          M_sm_d = CHECK_sm;
        end else begin
          M_sm_d = MOVE_sm;
        end
      end
      CHECK_sm: begin
        if (M_matrix_q == 64'h0000000000000000) begin
          M_alu_a = M_score_q;
          M_alu_b = M_level_q;
          M_alu_alufn = 6'h00;
          M_score_d = M_alu_out[0+3-:4];
          M_sm_d = WIN_sm;
        end else begin
          M_sm_d = MOVE_sm;
        end
      end
      WIN_sm: begin
        if (M_buttons_startpressed) begin
          M_sm_d = CHOOSE_LVL_sm;
        end
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_level_q <= 1'h0;
      M_current_q <= 1'h0;
      M_next_q <= 1'h0;
      M_matrix_q <= 1'h0;
      M_score_q <= 1'h0;
      M_sm_q <= 1'h0;
    end else begin
      M_level_q <= M_level_d;
      M_current_q <= M_current_d;
      M_next_q <= M_next_d;
      M_matrix_q <= M_matrix_d;
      M_score_q <= M_score_d;
      M_sm_q <= M_sm_d;
    end
  end
  
endmodule
