/*
   This file was generated automatically by the Mojo IDE version B1.3.3.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boolean_5 (
    input [7:0] a,
    input [7:0] b,
    input [3:0] alufn,
    output reg [7:0] op
  );
  
  
  
  integer i;
  
  reg [1:0] abi;
  
  always @* begin
    op = 8'h00;
    for (i = 1'h0; i < 8; i = i + 1) begin
      abi[1+0-:1] = b[(i)*1+0-:1];
      abi[0+0-:1] = a[(i)*1+0-:1];
      
      case (abi)
        2'h0: begin
          op[(i)*1+0-:1] = alufn[0+0-:1];
        end
        2'h1: begin
          op[(i)*1+0-:1] = alufn[1+0-:1];
        end
        2'h2: begin
          op[(i)*1+0-:1] = alufn[2+0-:1];
        end
        2'h3: begin
          op[(i)*1+0-:1] = alufn[3+0-:1];
        end
      endcase
    end
  end
endmodule
