/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module comparer_3 (
    input z,
    input v,
    input n,
    input alufn1,
    input alufn2,
    output reg [7:0] op
  );
  
  
  
  always @* begin
    op = 8'h00;
    if (alufn2 == 1'h0 & alufn1 == 1'h1) begin
      op[0+0-:1] = z;
    end else begin
      if (alufn2 == 1'h1 & alufn1 == 1'h0) begin
        op[0+0-:1] = n ^ v;
      end else begin
        if (alufn2 == 1'h1 & alufn1 == 1'h1) begin
          op[0+0-:1] = z | (n ^ v);
        end
      end
    end
  end
endmodule
