/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module multiply_6 (
    input [7:0] a,
    input [7:0] b,
    input alufn1,
    output reg [7:0] op
  );
  
  
  
  reg [15:0] tmpmult;
  
  always @* begin
    if (alufn1) begin
      tmpmult = a * b;
    end else begin
      tmpmult = a / b;
    end
    op = tmpmult[0+7-:8];
  end
endmodule
